### ISSUE TITLE
All videos downloaded with no audio and slowed down

### ISSUE THREAD

**Issue by leg0m4n** [AliaksandrSiarohin/video-preprocessing#40]
Hi, super devastating, have been downloading VoxCeleb for a few days with your script, but the resulting .mp4 audios downloaded without any audio(which is very important for my research) and slowed down to around 25%(this is fixable, but no audio is a real bummer).

**Comment by AliaksandrSiarohin** [comment]
Hi, the videos is supposed to be used as individual '.png' frames. So the audio and fps was not important for me.

If you want to preserve audio you will have to write the script that convert metadata to ffmpeg commands, then launch all these ffmpeg commands:
You can take inspiration from https://github.com/AliaksandrSiarohin/first-order-model/blob/83b86924a26fb4e061aeecac90fd792ed4d8f3d8/crop-video.py#L72
