### ISSUE TITLE
How to gen a metada.csv file?

### ISSUE THREAD

**Issue by tailangjun** [AliaksandrSiarohin/video-preprocessing#49]
I want to make a dataset, but don't kown how to gen a metada.csv file. can you give me same advice, thinks~

**Comment by AliaksandrSiarohin** [comment]
I generate it with crop_{dataset_name}.py file.

**Comment by tailangjun** [comment]
> I generate it with crop_{dataset_name}.py file.

ok，I will try it，thx~
