### ISSUE TITLE
Size of train dataset

### ISSUE THREAD

**Issue by Veselov-Ivan** [AliaksandrSiarohin/video-preprocessing#6]
Hi, Aliaksandr!

I've parsed your file vox-metadata.csv and found out, that condition [(width > 255) & (height > 255) & (length > 63)] gives 17703 train and  476 test videos.

Your paper says, that there were 12331 train and 444 test videos.
Could you please answer, why there is such a big difference in the number of training videos?

Code to reproduce:
```
import pandas as pd

df = pd.read_csv("vox-metadata.csv")

df['bbox1'], df['bbox2'], df['bbox3'], df['bbox4'] = df['bbox'].str.split('-').str
df[["bbox1", "bbox2", "bbox3", "bbox4"]] = \
    df[["bbox1", "bbox2", "bbox3", "bbox4"]].apply(pd.to_numeric)

df['w'] = df['bbox3'] - df['bbox1']
df['h'] = df['bbox4'] - df['bbox2']
df['len'] = df['end'] - df['start']

df_train_test = df[(df['w'] > 255) & (df['h'] > 255) & (df['len'] > 63)]
df_train = df_train_test[df_train_test['partition'] == 'train']
df_test = df_train_test[df_train_test['partition'] == 'test']

print(df_train.shape, df_test.shape)
```

**Comment by AliaksandrSiarohin** [comment]
Sorry, I believe there is an error in the paper it should be 19522 and 525. I will modify the paper accordingly. Thank you.
